baseURL = 'http://localhost:1313'
languageCode = 'ja-JP'
title = 'Salesforce Saturday Japan'
theme = "paper"

[params]
  twitter = 'sfsattokyo'
  github = 'salesforce-saturday-japan'
  rss = true
  name = 'Salesforce Saturday Japan'
  avatar = 'salesforcesaturdayjapan@gmail.com'
  bio = 'åœŸæ›œæ—¥ã«Salesforceã®å‹‰å¼·ã‚’ã—ãŸã„ã¿ãªã•ã‚“ã‚’ç¹‹ã’ã¦ä¸€ç·’ã«ç››ã‚Šä¸ŠãŒã‚‹ã“ã¨ãŒãƒŸãƒƒã‚·ãƒ§ãƒ³ã§ã™ğŸŒ '

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true